table AmtEarningPattern
	lineageTag: 8e341ec8-14ce-4f05-9807-02a703d63527

	column Channel
		dataType: string
		lineageTag: 7bc723d5-541b-4224-8ee0-3ab4a7168353
		sourceColumn: Channel

	column DevelopmentDays
		dataType: int64
		lineageTag: 2e52313a-9871-4861-9e22-137a9e3b2773
		sourceColumn: DevelopmentDays

	column EpText
		dataType: string
		lineageTag: a2e19fce-1a04-4b6a-be40-aad5def6e672
		sourceColumn: EpText

	column EpValue = IFERROR(VALUE(SUBSTITUTE(AmtEarningPattern[EpText], "%", "")) / 100, 0)
		dataType: double
		formatString: 0.00%
		lineageTag: fc3489d8-66bf-40d8-84c1-1f97bb81801d

	partition AmtEarningPattern = m
		mode: import
		source =
				let
				    Source = Sql.Database("2co7m4mimwiezlh3t4sejyt2uy-mcybvrzqd3tufdttrjbjhzokdi.datawarehouse.fabric.microsoft.com", "taurus_lakehouse"),
				    Data = Source{[Schema="bronze",Item="amt_earning_pattern"]}[Data],
				    Renamed = Table.RenameColumns(Data, {{"channel","Channel"},{"development_days","DevelopmentDays"},{"ep","EpText"}}),
				    Typed = Table.TransformColumnTypes(Renamed, {{"Channel", type text}, {"DevelopmentDays", Int64.Type}, {"EpText", type text}})
				in
				    Typed

