# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }

# CELL ********************

column_rename_map_tblSchemes = {
    "TravelSalesTransactionPersonID": "travel_sales_transaction_person_id",
    "TravelSalesTransactionID": "travel_sales_transaction_id",
    "ClientID": "client_id",
    "Title": "title",
    "Firstname": "first_name",
    "Surname": "surname",
    "DateofBirth": "date_of_birth",
    "AgeAtpolicyIssue": "age_at_policy_issue",
    "AgeAtpolicystart": "age_at_policy_start",
    "Gender": "gender",
    "Relationship": "relationship",
    "MedicallyScreened": "medically_screened",
    "ScreeningResult": "screening_result",
    "ScreeningScore": "screening_score",
    "MedicalGrossIncIPT": "medical_gross_inc_ipt",
    "MedicalGrossExcIPT": "medical_gross_exc_ipt",
    "MedicalNetToUnderwriter": "medical_net_to_underwriter",
    "MedicalIPT": "medical_ipt",
    "MedicalCommissionA": "medical_commission_a",
    "MedicalCommissionB": "medical_commission_b",
    "MedicalCommissionC": "medical_commission_c",
    "MedicalCommissionD": "medical_commission_d",
    "MedicalCommissionE": "medical_commission_e",
    "MedicalCommissionF": "medical_commission_f",
    "Deceased": "deceased"
}

column_rename_map_tblSchemeHeaders = {
    "SchemeHeaderID": "scheme_header_id",
    "Name": "name",
    "PolicyTypeID": "policy_type_id",
    "ByOrder": "by_order",
    "LargeLossThreshold": "large_loss_threshold",
    "PrinterID": "printer_id",
    "SpoolerId": "spooler_id",
    "ImportId": "import_id",
    "Picture": "picture",
    "AutoRenew": "auto_renew",
    "ProductTypeID": "product_type_id",
    "FriendlyName": "friendly_name",
    "IsCorporate": "is_corporate",
    "BookingDetailRequired": "booking_detail_required",
    "PolicyPlanID": "policy_plan_id",
    "UseLettersForRenewalEmail": "use_letters_for_renewal_email",
    "InsuranceTypeID": "insurance_type_id",
    "IsArchived": "is_archived",
    "SendAutoRenewalFailEmail": "send_auto_renewal_fail_email",
    "RenewMedicalScreening": "renew_medical_screening",
    "RenewToExistingAgent": "renew_to_existing_agent",
    "SendCustomerFailureEmail": "send_customer_failure_email",
    "RenewIfRescreenFails": "renew_if_rescreen_fails",
    "SetRulesForDifferentRenewalYears": "set_rules_for_different_renewal_years",
    "AutoRenewWithMedical": "auto_renew_with_medical",
    "SetRemindersByDestination": "set_reminders_by_destination",
    "MSSQL_System_Uniquifier_2066106401": "mssql_system_uniquifier_2066106401"
}

column_rename_map_tblTravelSalesTransactionPersons = {
    "TravelSalesTransactionPersonID": "travel_sales_transaction_person_id",
    "TravelSalesTransactionID": "travel_sales_transaction_id",
    "ClientID": "client_id",
    "Title": "title",
    "Firstname": "first_name",
    "Surname": "surname",
    "DateofBirth": "date_of_birth",
    "AgeAtpolicyIssue": "age_at_policy_issue",
    "AgeAtpolicystart": "age_at_policy_start",
    "Gender": "gender",
    "Relationship": "relationship",
    "MedicallyScreened": "medically_screened",
    "ScreeningResult": "screening_result",
    "ScreeningScore": "screening_score",
    "MedicalGrossIncIPT": "medical_gross_inc_ipt",
    "MedicalGrossExcIPT": "medical_gross_exc_ipt",
    "MedicalNetToUnderwriter": "medical_net_to_underwriter",
    "MedicalIPT": "medical_ipt",
    "MedicalCommissionA": "medical_commission_a",
    "MedicalCommissionB": "medical_commission_b",
    "MedicalCommissionC": "medical_commission_c",
    "MedicalCommissionD": "medical_commission_d",
    "MedicalCommissionE": "medical_commission_e",
    "MedicalCommissionF": "medical_commission_f",
    "Deceased": "deceased"
}

column_rename_map_tblTravelSalesTransactionOptions = {
    "TravelSalesTransactionOptionID": "travel_sales_transaction_option_id",
    "TravelSalesTransactionID": "travel_sales_transaction_id",
    "TravelSalesTransactionPersonID": "travel_sales_transaction_person_id",
    "OptionID": "option_id",
    "OptionName": "option_name",
    "OptionGrossIncIPT": "option_gross_inc_ipt",
    "OptionGrossExcIPT": "option_gross_exc_ipt",
    "OptionNetToUnderwriter": "option_net_to_underwriter",
    "OptionIPT": "option_ipt",
    "OptionCommissionA": "option_commission_a",
    "OptionCommissionB": "option_commission_b",
    "OptionCommissionC": "option_commission_c",
    "OptionCommissionD": "option_commission_d",
    "OptionCommissionE": "option_commission_e",
    "OptionCommissionF": "option_commission_f"
}

column_rename_map_tblTravelSalesTransactionCountries = {
    "TravelSalesTransactionCountryID": "travel_sales_transaction_country_id",
    "TravelSalesTransactionID": "travel_sales_transaction_id",
    "CountryName": "country_name",
    "ISOCode": "iso_code"
}


column_rename_map_tblTravelSalesTransactions = {
    "TravelSalesTransactionID": "travel_sales_transaction_id",
    "TransactionType": "transaction_type",
    "TransactionDate": "transaction_date",
    "CertificateID": "certificate_id",
    "PolicyNumber": "policy_number",
    "PolicyVersionNumber": "policy_version_number",
    "QuoteNumber": "quote_number",
    "QuoteRevisionNumber": "quote_revision_number",
    "AgentID": "agent_id",
    "AgentName": "agent_name",
    "CampaignID": "campaign_id",
    "CampaignName": "campaign_name",
    "PolicyType": "policy_type",
    "SchemeID": "scheme_id",
    "SchemeName": "scheme_name",
    "SchemeVersion": "scheme_version",
    "Destination": "destination",
    "HighestRatedCountry": "highest_rated_country",
    "FamilyGroup": "family_group",
    "TripValue": "trip_value",
    "StartDate": "start_date",
    "EndDate": "end_date",
    "Duration": "duration",
    "IssueDate": "issue_date",
    "QuoteDate": "quote_date",
    "CancellationDate": "cancellation_date",
    "CancellationReason": "cancellation_reason",
    "QuoteRequestGUID": "quote_request_guid",
    "ExternalReference": "external_reference",
    "LeadTitle": "lead_title",
    "LeadForename": "lead_forename",
    "LeadSurname": "lead_surname",
    "LeadAddress1": "lead_address_1",
    "LeadAddress2": "lead_address_2",
    "LeadAddress3": "lead_address_3",
    "LeadAddress4": "lead_address_4",
    "LeadAddress5": "lead_address_5",
    "LeadPostcode": "lead_postcode",
    "LeadEmail": "lead_email",
    "LeadTelNumber1": "lead_tel_number_1",
    "LeadTelNumber2": "lead_tel_number_2",
    "LeadDOB": "lead_dob",
    "HighestDOB": "highest_dob",
    "Residence": "residence",
    "Pax": "pax",
    "Adults": "adults",
    "Children": "children",
    "MedicalScreening": "medical_screening",
    "TotalGrossIncIPT": "total_gross_inc_ipt",
    "TotalGrossExcIPT": "total_gross_exc_ipt",
    "TotalNetToUnderwriter": "total_net_to_underwriter",
    "TotalIPT": "total_ipt",
    "TotalCommissionA": "total_commission_a",
    "TotalCommissionB": "total_commission_b",
    "TotalCommissionC": "total_commission_c",
    "TotalCommissionD": "total_commission_d",
    "TotalCommissionE": "total_commission_e",
    "TotalCommissionF": "total_commission_f",
    "BaseGrossIncIPT": "base_gross_inc_ipt",
    "BaseGrossExcIPT": "base_gross_exc_ipt",
    "BaseNetToUnderwriter": "base_net_to_underwriter",
    "BaseIPT": "base_ipt",
    "BaseCommissionA": "base_commission_a",
    "BaseCommissionB": "base_commission_b",
    "BaseCommissionC": "base_commission_c",
    "BaseCommissionD": "base_commission_d",
    "BaseCommissionE": "base_commission_e",
    "BaseCommissionF": "base_commission_f",
    "OptionGrossIncIPT": "option_gross_inc_ipt",
    "OptionGrossExcIPT": "option_gross_exc_ipt",
    "OptionNetToUnderwriter": "option_net_to_underwriter",
    "OptionIPT": "option_ipt",
    "OptionCommissionA": "option_commission_a",
    "OptionCommissionB": "option_commission_b",
    "OptionCommissionC": "option_commission_c",
    "OptionCommissionD": "option_commission_d",
    "OptionCommissionE": "option_commission_e",
    "OptionCommissionF": "option_commission_f",
    "MedicalGrossIncIPT": "medical_gross_inc_ipt",
    "MedicalGrossExcIPT": "medical_gross_exc_ipt",
    "MedicalNetToUnderwriter": "medical_net_to_underwriter",
    "MedicalIPT": "medical_ipt",
    "MedicalCommissionA": "medical_commission_a",
    "MedicalCommissionB": "medical_commission_b",
    "MedicalCommissionC": "medical_commission_c",
    "MedicalCommissionD": "medical_commission_d",
    "MedicalCommissionE": "medical_commission_e",
    "MedicalCommissionF": "medical_commission_f",
    "IPTRate": "ipt_rate",
    "MarketingPermissionA": "marketing_permission_a",
    "MarketingPermissionB": "marketing_permission_b",
    "MarketingPermissionC": "marketing_permission_c",
    "MarketingPermissionD": "marketing_permission_d",
    "MarketingPermissionE": "marketing_permission_e",
    "User": "user",
    "PolicyStatus": "policy_status",
    "Underwriter": "underwriter",
    "AutoRenewOptIn": "auto_renew_opt_in",
    "CampaignDiscount": "campaign_discount",
    "CampaignCommission": "campaign_commission",
    "CampaignCommissionB": "campaign_commission_b",
    "LastUpdatedBy": "last_updated_by",
    "PercentageCancellation": "percentage_cancellation",
    "ConvertedBy": "converted_by",
    "Currency": "currency",
    "AgentCode": "agent_code",
    "PolicyRenewalYear": "policy_renewal_year",
    "BrandIdentifier": "brand_identifier",
    "CampaignDescription": "campaign_description",
    "MarketingChannel": "marketing_channel",
    "ParentAgent": "parent_agent"
}

column_rename_map_tblTravelEnquiry = {
  "TravelEnquiryID": "travel_enquiry_id",
  "QuoteDate": "quote_date",
  "SourceCode": "source_code",
  "CampaignID": "campaign_id",
  "CampaignName": "campaign_name",
  "AgentID": "agent_id",
  "AgentName": "agent_name",
  "SchemeType": "scheme_type",
  "ExternalDestinationID": "external_destination_id",
  "MagentaDestinationID": "magenta_destination_id",
  "MagentaDestination": "magenta_destination",
  "GroupType": "group_type",
  "StartDate": "start_date",
  "EndDate": "end_date",
  "Duration": "duration",
  "HolidayValue": "holiday_value",
  "Residency": "residency",
  "AutorenewalOptIn": "autorenewal_opt_in",
  "BrandIdentifier": "brand_identifier",
  "CampaignDescription": "campaign_description",
  "MarketingChannel": "marketing_channel"
}


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
